# 该文件夹下有考生文件夹
# 最后一定要加上\\或/
examinee_folder="D:/"

# 考生列表（不考试的不用写）
list_of_candidates=["张三"]

# 检查项列表
# 序号从0开始！！！
checklist=[
    [
        "check text file content",
        "./云南宣传.txt",
        "云南&宣传\n\n1、七彩云南，山水画廊。苍山洱海映诗意，丽江古城诉千年。香格里拉秘境藏，元阳梯田绘云霞。过桥米线鲜香绕，普洱茶韵醉心田。\n\n2、25个民族织锦绣，四季如春候君来。人间仙境何处觅？云岭之南等你探……"
    ]
]

# 分数计算（如果填字符串，按照Python语法，否则会出错，还可以填列表）
score_calculation=[20]